# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.TimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('step', models.IntegerField(verbose_name='\u95f4\u9694\u65f6\u95f4(\u5355\u4f4d\u5206\u949f)')),
                ('enable', models.BooleanField()),
            ],
            options={
                'verbose_name': '\u6559\u7ec3',
            },
        ),
    ]
