# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.TimeField(verbose_name='\u9884\u7ea6\u65f6\u95f4')),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.TimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('step', models.IntegerField(verbose_name='\u65f6\u95f4\u95f4\u9694')),
                ('ceate_date', models.DateField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65e5\u7a0b',
                'verbose_name_plural': '\u65e5\u7a0b\u7ba1\u7406',
            },
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': '\u6559\u7ec3', 'verbose_name_plural': '\u6559\u7ec3'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='step',
        ),
        migrations.AddField(
            model_name='coach',
            name='account',
            field=models.CharField(default=datetime.datetime(2016, 3, 30, 8, 44, 33, 786068, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 3, 30, 8, 45, 1, 89600, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 3, 30, 8, 45, 15, 657304, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.Coach'),
        ),
        migrations.AddField(
            model_name='order',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.Coach'),
        ),
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.Student'),
        ),
    ]
