# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_auto_20160330_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u9884\u7ea6', 'verbose_name_plural': '\u9884\u7ea6\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '\u5b66\u5458', 'verbose_name_plural': '\u5b66\u5458'},
        ),
        migrations.AlterField(
            model_name='order',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='\u63a5\u53d7\u9884\u7ea6'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.Coach', verbose_name='\u6559\u7ec3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(verbose_name='\u9884\u7ea6\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.Student', verbose_name='\u5b66\u5458'),
        ),
    ]
